### PR TITLE
feat: Add a dice game 

### PR DESCRIPTION
**Pull request by aayush105**
# 🎲 Dice Game

This PR adds a simple **Dice Game** built using **React**. The game allows users to select a number, roll a dice, and score points based on their guess.

## How to Play:
1. Select any number from the available options.
2. Click on the dice to roll.
3. If the selected number matches the rolled dice, the user earns points equal to the dice value. If not, 2 points are deducted.

## Features:
- Random number generation for the dice.
- Score tracking with a reset option.
- Toggle to show/hide game rules.
- Clean UI built with styled-components.

### Main Screen:
Screenshot 2024-10-08 152831

### Rolling the Dice:
Screenshot 2024-10-08 152927

### Game Result:
Screenshot 2024-10-08 152913

### CODE REVIEW

**Comment by aloukikjoshi** [comment]
One of the best pull request till now. Thanks for the great contribution.

**Comment by aloukikjoshi** [comment]
Also if you are good at Next.js I would like to collaborate with you on some projects I am working on!

**Comment by aayush105** [comment]
> One of the best pull request till now. Thanks for the great contribution.

Thank you @aloukikjoshi

**Comment by aayush105** [comment]
> Also if you are good at Next.js I would like to collaborate with you on some projects I am working on!

Yes, sure i will love to work and contribute to the project. @aloukikjoshi

**Pull request merged**
